# MoFuSS
# Windows version
# Date: Mar 2023

# All needed packages for MoFuSS
library(animation)
library(bitops)
library(caTools)
library(colorspace)
library(data.table)
library(dplyr)
library(fasterize)
library(fBasics)
library(fields)
library(furrr)
library(ggplot2)
library(gitlabr)
library(glue)
library(gridExtra)
library(gstat)
library(htmltools)
library(htmlwidgets)
library(httpuv)
library(igraph)
library(inline)
library(jpeg)
library(knitr)
#library(lattice)
#library(latticeExtra)
#library(maptools)
library(mapview)
library(msm)
library(plyr)
library(png)
library(purrr)
library(raster)
# library(rasterVis)
library(rbenchmark)
library(Rcpp)
library(RcppProgress)
library(RCurl)
library(reader)
library(readr)
# library(rgdal)
# library(rgeos)
library(rgl)
# library(rgrass7)
library(rmarkdown)
library(sf)
library(snow)
library(sp)
library(spam)
library(stars)
library(stringr)
library(svDialogs)
library(tcltk)
library(tictoc)
library(tidyverse)
library(tiff)
library(timeDate)
library(tools)
library(XML)
